### ISSUE TITLE
# -*- conding: utf-8 -*-

### ISSUE THREAD

**Issue by deinok** [Doasy/Simple-WebScraping#1]
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-
# -*- conding: utf-8 -*-

Es coding
# -*- coding: utf-8 -*-

**Comment by Doasy** [comment]
DISLEXIA AGAIN (o algo)

Gràcies ;)
