### ISSUE TITLE
#!/user/bin/env python

### ISSUE THREAD

**Issue by deinok** [Doasy/Simple-WebScraping#2]
#!/user/bin/env python
#!/user/bin/env python
#!/user/bin/env python
#!/user/bin/env python
#!/user/bin/env python
#!/user/bin/env python
#!/user/bin/env python
#!/user/bin/env python
#!/user/bin/env python

Vols dir que no es
#!/usr/bin/env python

**Comment by Doasy** [comment]
dislexia.

MERCI
